### ISSUE TITLE
Setup continuous deployment

### ISSUE THREAD

**Issue by sebmarste** [Rostlab/JS18_ProjectA_Group1#5]
when a branch is merged into development (and all test finished successfully) the new code is deployed directly and running on the public development page

**Comment by syxolk** [comment]
I configured the Git username/password in travis. Your demo is here:
http://js2018-group1.azurewebsites.net/

**Comment by syxolk** [comment]
There's one issue once you start using Postgres: We don't yet have any managed database instance yet.

**Comment by syxolk** [comment]
Manual deployment currently fails with this error message:

```
remote: > nlp-graph@1.0.0 postinstall /home/site/wwwroot
remote: > npm run build:production
remote: 
remote: 
remote: > nlp-graph@1.0.0 build:production /home/site/wwwroot
remote: > gulp build --production
remote: 
remote: .................
remote: module.js:471
remote:     throw err;
remote:     ^
remote: 
remote: Error: Cannot find module 'gulp-babel'
remote:     at Function.Module._resolveFilename (module.js:469:15)
remote:     at Function.Module._load (module.js:417:25)
remote:     at Module.require (module.js:497:17)
remote:     at require (internal/module.js:20:19)
remote:     at Object.<anonymous> (/home/site/wwwroot/gulpfile.js:8:13)
remote:     at Module._compile (module.js:570:32)
remote:     at Object.Module._extensions..js (module.js:579:10)
remote: An error has occurred during web site deployment.
remote:     at Module.load (module.js:487:32)
remote: npm failed
remote:     at tryModuleLoad (module.js:446:12)
remote:     at Function.Module._load (module.js:438:3)
```

**Comment by syxolk** [comment]
What kind of database are you going to use? Do you need it now or later?

**Comment by sebmarste** [comment]
@syxolk we are using postgres and it would be great to get it soon ;)

**Comment by syxolk** [comment]
Ok, I will do my best.

**Comment by syxolk** [comment]
I had to recreate your app service to include a postgresql instance.
The PostgreSQL version is 9.6.
I configured DB_HOST, DB_USER, DB_PASSWORD and DB_NAME as environment variables in the app's settings.

**Comment by syxolk** [comment]
I executed knex migration locally using the Azure database:
```
Working directory changed to ~/JS18_ProjectA_Group1/server
Migrate
Create generic_dataset
Create generic_dataset
Register human_resources__core_dataset
Insert data into human_resources__core_dataset
Insert data into human_resources__core_dataset finished
Batch 1 run: 1 migrations 
~/JS18_ProjectA_Group1/server/migrations/migrations.js
```

![image](https://user-images.githubusercontent.com/6666063/37006835-9298cb1a-20da-11e8-830b-c12474da5e26.png)

Problem: Table `human_resources__core_dataset` contains 0 rows?!

**Comment by sebmarste** [comment]
Great, that means that the DB is successfully installed! 👍 
there was a concurrency bug, but this should be solved in our feature branches (I discovered this yesterday as well...)
1) node runs the migrations automatically on every serverstart
2) is there a possibility that we can run the rollback/migration manually (and have a look at the output/result)?

**Comment by syxolk** [comment]
1. Great, didn't know that.
2. I could either give you the postgres connection parameters (it's currently open to the public anyway) or I could create an IAM user in Azure.
