### ISSUE TITLE
implement testing based on test cases in commands.json

### ISSUE THREAD

**Issue by r-sukanya** [Rostlab/JS18_ProjectA_Group1#54]

**Comment by romikps** [comment]
hi, @r-sukanya! could you please let me know, at the moment, how many percent of your planned test coverage would you say you already have?

**Comment by r-sukanya** [comment]
I would say about 30%, I plan to complete it be thursday.

**Comment by TobiasPr** [comment]
We will also need some commands for the second dataset and tests as well, the commands should be more or less copy-paste
