### ISSUE TITLE
Add Different Test Cases for NLP Functionality

### ISSUE THREAD

**Issue by grillmann** [Rostlab/JS18_ProjectA_Group1#58]
Test Transformation Functions; Test Edge Cases that also might fail

**Comment by romikps** [comment]
hi, @grillmann! at the moment, how many percent of your planned test coverage would you say you already have? just to know your current standing

**Comment by grillmann** [comment]
Hey @romikps, after featur branch 19 is merged i will create some more Tests for the column operations but i will probably be done with that by tomorrow evening
