### ISSUE TITLE
Azure deployment npm install fails

### ISSUE THREAD

**Issue by TobiasPr** [Rostlab/JS18_ProjectA_Group1#72]
Deployment fails with following error log:

Running "node" "/usr/bin/npm-cli.js" install --production        
remote: ................
remote: npm ERR! addLocal Could not install /tmp/npm-246-6bfca9e3/git-cache-d7c08c6d/3e70b4b3e0395f14887a88b5cfeec86e2f351c32        
remote: npm ERR! Linux 4.4.0-112-generic        
remote: An error has occurred during web site deployment.        
remote: npm ERR! argv "/opt/nodejs/6.11.0/bin/node" "/usr/bin/npm-cli.js" "install" "--production"        
remote: npm failed        
remote: npm ERR! node v6.11.0        
remote: npm ERR! npm  v3.10.10

**Comment by syxolk** [comment]
Do you need help from me?

**Comment by syxolk** [comment]
Here's the documentation for using a Github dependency: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
